language: node_js
node_js:
- node
deploy:
  provider: npm
  skip_cleanup: true
  email: nicolas.vanhoren@gmail.com
  api_key:
    secure: M67mOpsLSPpqyAn0k5eLH3+VM5x3/KctJ8lGd6/Tkq/e7yvmyQclKBYmJNytgJIfOmZ4oYNPs51HZB5ktOa8+tQlky3fOc6lVadwJiyKOlA8kLmiPD8X299utKRXqGQwGDrRKdaAk6ropP/63bJTdNWwi/le2vIpXVqBoqYs2U87b5i2wmgfLuVLWXwCwsPj3Mv8GkO7wKtRULeH+9y5hkpsPrvhFIftU4wEuYQdiSzOxSCXY0zRAZ+Jw8W/wi2k5yxr4V9MsvjoufabBBLQ31M5D/3wmKZMqlkkFk/xaerzfCoOI2q+3fK8vcX0RIGCRb3WaCaPlLROHHnH+7AcNMNiqwAy3OSUF9Yy2u9Ea44+JZ0UnQRhMbJy6pORrf15ga3/lQvn0ZhYuiT7p6+b3LDhgWsXH7N7DU2pZiiA8ni5oL/vD8yoLDHo7V/IKjOJlps9nJhDlkRCqbWNoSXZ5RZ6F/A4lS7LY+20lV1QNia67fYDHoDVb0hgjIZad2Bq56lGHICZ3d0y2XVJCgmk/Fc13Xuy6f/OJW5e80UFt1c8Xt7NiK8O9iKNFi7FyXfU7A2o+IFOrWyrWkJPyAh/5ttvdgA5crgviEq6iCoGCnNbs2ARIr5tmXbZ+yw9mk/0+qgEG/yEmEpE6WU4rUJ2BUNiNkF++Xxi5ZjxnbT+QxI=
  on:
    tags: true
    repo: nicolas-van/ring
    branch: master
