language: node_js
node_js:
- node
deploy:
  provider: npm
  skip_cleanup: true
  email: nicolas.vanhoren@gmail.com
  api_key:
    secure: NswBFZ8qN/VFJ3YgHnFZh/GmeEHH9F1D8FzuUwVPiuIa1bmtBexUBGMwhNgl3mzDgJ28Tdiy5uwfSN93e/+sNfb4tEdQjG63GQ4sMFEhKkGV51lop7HsJe+1JmFSbuWINW7bimbHnq4twmplyRNwu4MLlnwrAfKuKY+YXkre46Ly8BWdaIeqJcgoUUI62CZLuzYThp1gERJ+tLQ6P7J5xlhAJUWtUgbbKqY4/IYT1OjKjeIB08B88SKdueAGjWA9yFBe31Z1iDkm/hRDguKyksWFEN1ETgx7LBp4nyjHXrvZ2CfuJxTY7nFvW6lDFl/lto85ecVm9TI+mNvMaZS1A9tNe6PwNmn/Lv+gspSbGZ1ap8nOp2Q0hmM9yRq0ailNjZKZgK4iSvsgNZ6U/U4bjmT13ejn+5SF41OrMttfCWJbCSQfkScp4Rem7rm3XMgGlJs99FxfRFs+gi/erdtZbdOBehEmi/vvNPKGy9r1aRuBzeaanf3mQMOo6IDL4nRFqj9EcAaW/DY+2Lhfc4IGfVtybGG+VLyu/qhMyg/Ix6mHyQRR9cjnn5qDblrWRAEuWwwq8J213Koc39K84HxOJ31uTPY9mWS3UFIm3Q1tbcq+gaHyaywIeBdZyWe5lX1ygS8JCPSSX9ipGgXQN2FhiyZvoNT6hAwK/c/1cTzH8Zc=
  on:
    tags: true
    repo: nicolas-van/ring.js
    branch: master
